trigger: none

pool:
  name: Linux-agent

variables:
  azureSubscription: 'b4bb6c40-9ae9-48f8-ba74-bba33613049a'
  webClientAppName: 'motormate-frontend-web-client'
  webAdminAppName: 'motormate-frontend-web-admin'

stages:
- stage:
  displayName: "Build and Deploy MotorMate Admin and Client"
  jobs:
  - job: Client 
    displayName: "Build and Deploy"
    steps:
    - task: Npm@1
      displayName: "Npm install"
      inputs:
        command: 'install'
        workingDir: '$(System.DefaultWorkingDirectory)/client'
    
    - task: Npm@1
      displayName: "Npm run build"
      inputs:
        command: 'custom'
        workingDir: '$(System.DefaultWorkingDirectory)/client'
        customCommand: 'npm run build --if-present'

    - task: ArchiveFiles@2
      displayName: "Archive client solution"
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/client/build'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(System.DefaultWorkingDirectory)/client.zip'
        replaceExistingArchive: true
      
    - task: AzureWebApp@1
      displayName: "Deploy to $(webClientAppName)"
      inputs:
        azureSubscription: 'DunDon Free Subcription (cfd7c513-8b41-4dc8-b1ed-69bad9822f7d)'
        appType: 'webAppLinux'
        appName: $(webClientAppName)
        package: '$(System.DefaultWorkingDirectory)/client.zip'
        runtimeStack: 'NODE|16-lts'